name: Build-EXE

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
      
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3.3.0
      
      - name: Setup Python
        uses: actions/setup-python@v4.5.0
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Build EXE
        uses: Nuitka/Nuitka-Action@main
        with:
          script-name: portal_snake.py
          onefile: true
          include-module: |
            pygame
            pygame._view
            background
            eat
            music
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v3.1.2
        with:
          name: ${{ runner.os }} Build
          path: |
            build/*.exe
